name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt